### ISSUE TITLE
Error in classification step: Index out of bounds in similarity evaluation

### ISSUE THREAD

**Issue by hjkim666** [zamanzadeh/CARLA#4]
Hello, esteemed author,

I encountered an error while running this code, so I’m reaching out for assistance.

**First, the following command worked fine:**

```bash
python3 carla_pretext.py --config_env configs/env.yml --config_exp configs/pretext/carla_pretext_msl.yml --fname M-6
```
However, the second command is where I encountered an issue:

```
python3 carla_classification.py --config_env configs/env.yml --config_exp configs/classification/carla_classification_msl.yml --fname M-6
```
The error is as follows:

-----------------------------------------------------------------
- Get dataset and dataloaders for SMAP dataset - timeseries M-6
/workspace/CARLA/data/MSL.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  length = row[-1]
-- Train samples size: 1365 - Test samples size: 1849

- Model initialisation
-- No checkpoint file at results/SMAP/M-6/classification/checkpoint.pth.tar -- new model initialised

- Training:
-- Epoch 1/50
/workspace/CARLA/models/resent_time.py:25: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv1d(input=input, weight=weight, bias=bias, stride=stride,
/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Epoch: [1][ 0/27] Total Loss -1.1340e+01 (-1.1340e+01)  Consistency Loss 2.2327e+00 (2.2327e+00)        Inconsistency Loss 2.2427e+00 (2.2427e+00) Entropy 2.2660e+00 (2.2660e+00)
[Out of bound]anchors:torch.Size([1365])  neighbors:torch.Size([1365])
Traceback (most recent call last):
  File "/workspace/CARLA/carla_classification.py", line 237, in <module>
    main()
  File "/workspace/CARLA/carla_classification.py", line 203, in main
    classification_stats = classification_evaluate(predictions)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/CARLA/utils/evaluate_utils.py", line 145, in classification_evaluate
    similarity = similarity[anchors, neighbors]
IndexError: index 2332 is out of bounds for dimension 1 with size 1365

Potential Cause
The issue seems to be that neighbors increases to twice the size of the data.

I looked into the code and found that in carla_pretext.py, there is a line:

ts_repository_aug = TSRepository(len(base_dataset) * 2,
                                     p['model_kwargs']['features_dim'],
                                     p['num_classes'], p['criterion_kwargs']['temperature']) 

When I changed len(base_dataset) * 2 to len(base_dataset), the error was resolved. I assume you doubled the size because you were generating neighbors, but would it be alright to run it with my modification? It doesn't seem to align with the intention of your algorithm, so I would appreciate some clarification.

Thank you for your assistance!

**Comment by zamanzadeh** [comment]
Thanks for raising the issue. The issue is now resolved. Please check the updated code.

**Comment by hjkim666** [comment]
Thank you for the quick update.
I have one more question. Could you let me know how to use a custom dataset?
I have a dataset that is categorized into normal/anomaly. It contains about 100,000 records and is labeled data. I would greatly appreciate it if you could explain how to use the yml file and custom_data.py for this.

Thank you in advance.

**Comment by 11baqijiangjiang** [comment]
> 感谢您的快速更新。我还有一个问题。你能告诉我如何使用自定义数据集吗？我有一个数据集，分为正常/异常。它包含大约 100,000 条记录并被标记为数据。如果您能解释如何使用 yml 文件并为此custom_data.py，我将不胜感激。
> 
> 先谢谢你。

你好  请问您复现成功了吗
